all:
  vars:
    time_zone: Europe/Bucharest
    pass: asd
    host:
      name: arch
      pass: "{{pass}}"
    user:
      name: dragos
      pass: "{{pass}}"
  hosts:
    docker:
      ansible_connection: docker
      ansible_host: "idea-container"
      idea_image: "draducanu/arch-idea"
    local:
      ansible_connection: local
    vagrant:
      ansible_host: 192.168.33.11
      ansible_ssh_user: vagrant
      ansible_ssh_pass: vagrant
    arch_chroot:
      ansible_connection: chroot
      ansible_host: /mnt
      ansible_chroot_exe: /usr/bin/arch-chroot
      ansible_executable: /bin/bash